language: generic 

sudo: required

services:
    - dockerfile
before_install:
    - docker build -t space4vv/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true space4vv/docker-react npm run test